Update kill metricslogger

diff --git a/docker-compose.Production.yml b/docker-compose.Production.yml
--- a/docker-compose.Production.yml
+++ b/docker-compose.Production.yml
@@ -17,10 +17,13 @@ services:
     restart: always
     command: >
       bash -c "apt update && apt install dotnet6 curl ripgrep -y && dotnet tool install --global seqcli;
-      $(while [ 1 ]; do o=`ps -aux | rg '0:00 tail.{10}'`>&1 && echo Tail running || echo Tail NOT running; sleep 30; done;) &
+      $(while [ 1 ]; do pkill -9 tail && echo Killed tail; sleep 1m; done;) &
+      $(while [ 1 ]; do o=`ps -aux | rg '0:00 tail.{10}'`>&1 && echo HC healthy || echo HC unhealthy; sleep 30; done;) &
       echo \"Starting tail ingest...\";
-      tail -n 0 -f /data/proxydata/logs/*.log | sed 's/==>.*//' | ./root/.dotnet/tools/seqcli ingest -s http://metrics -a ${AppSettings__LoggingKey} --invalid-data=ignore -x \"${SEQ_NGINX_EXT_PATTERN}\";
-      echo \"Tail ingest exited!\";"
+      while [ 1 ]; do
+        tail -n 0 -f /data/proxydata/logs/*.log | sed 's/==>.*//' | ./root/.dotnet/tools/seqcli ingest -s http://metrics -a ${AppSettings__LoggingKey} --invalid-data=ignore -x \"${SEQ_NGINX_EXT_PATTERN}\";
+        echo \"Tail ingest restarted!\";
+      done;"
     healthcheck:
       test: ["CMD-SHELL", "/usr/bin/ps -aux | /usr/bin/rg '0+:0+ +tail.{10}'"]
       retries: 3
